/**
 * MELO n8n Executor (Node.js)
 * 
 * This module is designed to be used by the MELO Decision Engine.
 * It takes an ActionRequest generated by the LLM, sends it to the n8n tool router,
 * and returns the structured ActionResult.
 */

const N8N_WEBHOOK_URL = 'http://localhost:5678/webhook/19818de0-d19a-45e9-b2a7-d7acf9c24e03';
// Note: If testing locally, use /webhook-test/ instead of /webhook/

/**
 * Executes a tool via n8n.
 * 
 * @param {string} taskId - The ID of the overarching task.
 * @param {string} actionId - The ID of this specific action attempt.
 * @param {string} actionName - The name of the tool to run (e.g. "web_search").
 * @param {object} parameters - The input schema for the tool.
 * @returns {Promise<object>} The standard ActionResult object.
 */
async function executeTool(taskId, actionId, actionName, parameters) {
    const actionRequest = {
        task_id: taskId,
        action_id: actionId,
        action: actionName,
        reason: `Executing ${actionName} requested by MELO Brain`,
        parameters: parameters
    };

    try {
        const response = await fetch(N8N_WEBHOOK_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(actionRequest)
        });

        if (!response.ok) {
            throw new Error(`n8n responded with status: ${response.status}`);
        }

        const actionResult = await response.json();
        return actionResult;

    } catch (error) {
        // Return a gracefully failing ActionResult if n8n is unreachable
        return {
            task_id: taskId,
            action_id: actionId,
            success: false,
            data: null,
            error: {
                code: "EXECUTION_FAILURE",
                message: error.message
            },
            metadata: {
                tool: actionName
            }
        };
    }
}

module.exports = { executeTool };
