import urllib.request
import json

# MELO n8n Executor (Python)
# 
# This module is designed to be used by the MELO Decision Engine.
# It takes an ActionRequest generated by the LLM, sends it to the n8n tool router,
# and returns the structured ActionResult.

N8N_WEBHOOK_URL = 'http://localhost:5678/webhook/19818de0-d19a-45e9-b2a7-d7acf9c24e03'
# Note: If testing locally, use /webhook-test/ instead of /webhook/

def execute_tool(task_id: str, action_id: str, action_name: str, parameters: dict) -> dict:
    """
    Executes a tool via n8n.
    
    :param task_id: The ID of the overarching task.
    :param action_id: The ID of this specific action attempt.
    :param action_name: The name of the tool to run (e.g. "web_search").
    :param parameters: The input schema for the tool.
    :return: The standard ActionResult dict.
    """
    action_request = {
        "task_id": task_id,
        "action_id": action_id,
        "action": action_name,
        "reason": f"Executing {action_name} requested by MELO Brain",
        "parameters": parameters
    }

    try:
        req = urllib.request.Request(
            N8N_WEBHOOK_URL,
            data=json.dumps(action_request).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result
    except Exception as e:
        # Return a gracefully failing ActionResult if n8n is unreachable
        return {
            "task_id": task_id,
            "action_id": action_id,
            "success": False,
            "data": None,
            "error": {
                "code": "EXECUTION_FAILURE",
                "message": str(e)
            },
            "metadata": {
                "tool": action_name
            }
        }
